# Default values for hr-system.

backend:
  image:
    repository: zaikbros/hr-backend
    tag: v2.0.0
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

frontend:
  image:
    repository: zaikbros/hr-frontend
    tag: v2.0.0
    pullPolicy: Always
  service:
    port: 80
  replicaCount: 1

mysql:
  image:
    repository: mysql
    tag: 8.0
  rootPassword: manager
  database: SpringbootJpa
  storage:
    size: 1Gi
    className: standard-rwo # Standard GKE storage class

certManager:
  email: syedkhaleel128@froster.com

ingress:
  host: hr.froster.com
  www: true
