apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-backend"
spec:
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-backend"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-backend"
    spec:
      initContainers: # wait for db to be ready
        - name: wait-for-db
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup db && nc -z db 3306; do echo waiting for mysql; sleep 2; done;",
            ]
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/SpringbootJpa
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: "{{ .Release.Name }}-backend"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: "{{ .Release.Name }}-backend"
