# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "{{ .Release.Name }}-certificate"
#   namespace: {{ .Release.Namespace }}
# spec:
#   secretName: hr-system-tls
#   issuerRef:
#     name: "{{ .Release.Name }}-letsencrypt"
#     kind: ClusterIssuer
#   commonName: {{ .Values.ingress.host }}
#   dnsNames:
#     - {{ .Values.ingress.host }}
# {{- if .Values.ingress.www }}
#     - www.{{ .Values.ingress.host }}
# {{- end }}
