# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: "{{ .Release.Name }}-letsencrypt"
# spec:
#   acme:
#     email: {{ .Values.certManager.email }}
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: "{{ .Release.Name }}-letsencrypt-key"
#     solvers:
#       - http01:
#           ingress:
#             class: nginx
